kind: Kustomization

resources:
  - ../../base
  
namePrefix: staging-
commonLabels:
 variant: staging
commonAnnotations:
  note: “Staging Image”
patches:
- path: deployment.yaml
  target:
    kind: Deployment
