pipeline:
    name: Deploy Build Infra
    identifier: Deploy_Build_Infra
    projectIdentifier: Spring_Forward
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy Build Infra
              identifier: Deploy_Build_Infra
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: Spring_Forward
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: Build_Cache
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: githubsuranc
                                                    gitFetchType: Branch
                                                    paths:
                                                        - infra/build-cache/cache.yaml
                                                    repoName: spring-forward-harness-example
                                                    branch: master
                  infrastructure:
                      environmentRef: Dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: springforwardk8sconnector
                              namespace: chris-builds
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
