FROM openjdk:27-ea-trixie
COPY application.yml /app/application.yml
COPY target/spring-forward-0.0.1-SNAPSHOT.jar /app/spring-forward-0.0.1-SNAPSHOT.jar
WORKDIR /app
CMD java -jar /app/spring-forward-0.0.1-SNAPSHOT.jar
