{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-forward.fullname" . }}
  labels:
    {{- include "spring-forward.labels" . | nindent 4 }}
    serviceMonitorSelector: prometheus
spec:
  selector:
    matchLabels:
      {{- include "spring-forward.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: "/actuator/prometheus"
{{- end }}
