kind: Kustomization

resources:
  - ../../base

namePrefix: production-
commonLabels:
 variant: production
commonAnnotations:
  note: “Production Image”
patches:
- path: deployment.yaml
  target:
    kind: Deployment
