---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-forward
  namespace: gitops-team-2
  labels:
    app.kubernetes.io/name: spring-forward
    app.kubernetes.io/instance: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-forward
      app.kubernetes.io/instance: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-forward
        app.kubernetes.io/instance: example
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: spring-forward
          securityContext:
            {}
          image: "ghcr.io/suranc/spring-forward-harness-example:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 400m
              memory: 350Mi
            requests:
              cpu: 400m
              memory: 350Mi
