---
apiVersion: v1
kind: Service
metadata:
  name: spring-forward
  labels:
    app.kubernetes.io/name: spring-forward
    app.kubernetes.io/instance: example
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: spring-forward
    app.kubernetes.io/instance: example
